budget: 1000000
optimizer: greedy
random_seed: 42
num_assets: 150
output_dir: outputs

# Column names when using a custom CSV
columns:
  name: name
  latitude: lat
  longitude: lon
  pof: pof
  cof: cof
  cost: cost
  condition: condition_score
